//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Родовые_сертификаты.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.16.172")]
        public string server {
            get {
                return ((string)(this["server"]));
            }
            set {
                this["server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
            set {
                this["user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fg67klbn0")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RodCertificate")]
        public string database {
            get {
                return ((string)(this["database"]));
            }
            set {
                this["database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2309039134")]
        public string INN_LPU {
            get {
                return ((string)(this["INN_LPU"]));
            }
            set {
                this["INN_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2303151117")]
        public string RegNumb_LPU {
            get {
                return ((string)(this["RegNumb_LPU"]));
            }
            set {
                this["RegNumb_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230901001")]
        public string KPP_LPU {
            get {
                return ((string)(this["KPP_LPU"]));
            }
            set {
                this["KPP_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1022301425629")]
        public string OGRN_LPU {
            get {
                return ((string)(this["OGRN_LPU"]));
            }
            set {
                this["OGRN_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ГБУЗ \'Детская краевая клиническая больница\' МЗ КК")]
        public string Name_LPU {
            get {
                return ((string)(this["Name_LPU"]));
            }
            set {
                this["Name_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350007, г. Краснодар, ул. пл. Победы, 1")]
        public string Address_LPU {
            get {
                return ((string)(this["Address_LPU"]));
            }
            set {
                this["Address_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Государственное")]
        public string Type_LPU {
            get {
                return ((string)(this["Type_LPU"]));
            }
            set {
                this["Type_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Клещенко Е.И.")]
        public string OwnDoc_LPU {
            get {
                return ((string)(this["OwnDoc_LPU"]));
            }
            set {
                this["OwnDoc_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сидорова Т.Н.")]
        public string OwnBookKeep {
            get {
                return ((string)(this["OwnBookKeep"]));
            }
            set {
                this["OwnBookKeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40601810900003000001")]
        public string RS_LPU {
            get {
                return ((string)(this["RS_LPU"]));
            }
            set {
                this["RS_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Минфин КК (ГБУЗ ДККБ, л/с 828.51.185.0) ЮЖНОЕ ГУ БАНКА РОССИИ г. Краснодар, назна" +
            "чение платежа - 82800000000000000 130, КОСГУ 131, Тип средств - 20.02.00")]
        public string BankName_LPU {
            get {
                return ((string)(this["BankName_LPU"]));
            }
            set {
                this["BankName_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("040349001")]
        public string BIK_LPU {
            get {
                return ((string)(this["BIK_LPU"]));
            }
            set {
                this["BIK_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KS_LPU {
            get {
                return ((string)(this["KS_LPU"]));
            }
            set {
                this["KS_LPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2308007718")]
        public string INN_FSS {
            get {
                return ((string)(this["INN_FSS"]));
            }
            set {
                this["INN_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230901001")]
        public string KPP_FSS {
            get {
                return ((string)(this["KPP_FSS"]));
            }
            set {
                this["KPP_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ГУ - КРО ФСС РФ")]
        public string Name_FSS {
            get {
                return ((string)(this["Name_FSS"]));
            }
            set {
                this["Name_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350033, г. Краснодар, ул. Ставропольская, 82")]
        public string Address_FSS {
            get {
                return ((string)(this["Address_FSS"]));
            }
            set {
                this["Address_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40402810903490000001")]
        public string RS_FSS {
            get {
                return ((string)(this["RS_FSS"]));
            }
            set {
                this["RS_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Южное ГУ Банка России по Краснодарскому краю г. Краснодар")]
        public string BankName_FSS {
            get {
                return ((string)(this["BankName_FSS"]));
            }
            set {
                this["BankName_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("040349001")]
        public string BIK_FSS {
            get {
                return ((string)(this["BIK_FSS"]));
            }
            set {
                this["BIK_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KS_FSS {
            get {
                return ((string)(this["KS_FSS"]));
            }
            set {
                this["KS_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("023")]
        public string DocNumb_FSS {
            get {
                return ((string)(this["DocNumb_FSS"]));
            }
            set {
                this["DocNumb_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.12.2018")]
        public string DocDate_FSS {
            get {
                return ((string)(this["DocDate_FSS"]));
            }
            set {
                this["DocDate_FSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 60")]
        public string eventType_id {
            get {
                return ((string)(this["eventType_id"]));
            }
            set {
                this["eventType_id"] = value;
            }
        }
    }
}
